/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cyhal.h"
#include "cybsp.h"
#include "cy_retarget_io.h"
#include "cy_log.h"

#include "bootutil.h"
#include "cy_ota_storage.h"

#include "flash_map_backend.h"
#include "sysflash.h"

#include "aws_ota_mqtt.h"

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* Flash Map Descriptors */
static const struct flash_area bootloader =
{
    .fa_id        = FLASH_AREA_BOOTLOADER,
    .fa_device_id = FLASH_DEVICE_INTERNAL_FLASH,
    .fa_off       = 0x107F0000,                         /* start address of dual bank manager */
    .fa_size      = 0x2000
};

static const struct flash_area bank_A =
{
    .fa_id        = FLASH_AREA_IMAGE_PRIMARY(0),
    .fa_device_id = FLASH_DEVICE_INTERNAL_FLASH,
    .fa_off       = 0x10000000,                         /* start address of active bank */
    .fa_size      = 0x3F8000                            /* size of the bank */
};

static const struct flash_area bank_B =
{
    .fa_id        = FLASH_AREA_IMAGE_SECONDARY(0),
    .fa_device_id = FLASH_DEVICE_INTERNAL_FLASH,
    .fa_off       = 0x12000000,                         /* start address of inactive bank */
    .fa_size      = 0x3F8000                            /* size of the bank */
};

const struct flash_area *boot_area_descs[] =
{
    &bootloader,
    &bank_A,
    &bank_B,
    NULL
};

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/**********************************************************************************************************************
 * Function Name: checkBank
 * Summary:
 *  Check consistency between current bank mode and the flash marker on Work Flash.
 *  When a mismatch is detected, the flash marker will be corrected to current bank mode.
 * Parameters:
 *  none
 * Return:
 *  int - result (0: no correction, 1: corrected marker, -1: failure)
 **********************************************************************************************************************
 */
static int checkBank(void)
{
    int ret = -1;

    /* get current bank mode */
    cy_en_bankmode_t bankmode = Cy_Flashc_GetMainBankMode();

    /* the bank mode should be dual-bank */
    if (bankmode != CY_FLASH_SINGLE_BANK_MODE)
    {
        /* get current map type */
        cy_en_maptype_t  maptype  = (cy_en_maptype_t)_FLD2VAL(FLASHC_FLASH_CTL_MAIN_MAP,FLASHC_FLASH_CTL);

        uint32_t marker[4];
        memcpy(marker, (void *)0x14012000, sizeof(marker));

        /* check if the map type matches the marker */
        if (((marker[0] == 0xAAAAAAAA) && (maptype == CY_FLASH_MAPPING_A)) ||
            ((marker[0] != 0xAAAAAAAA) && (maptype == CY_FLASH_MAPPING_B)))
        {
            /* correct the marker if mismatch */
            printf("Roll-backed to old version... correcting marker value\n");
            if (boot_set_pending(0, 1) == 0)
            {
                printf("Marker correction done\n");
                ret = 1;
            }
            else
            {
                printf("Failed to correct bank marker..\n");
            }
        }
        else
        {
            /* The new firmware has been validated */
            cy_awsport_ota_flash_image_validate();
            ret = 0;
        }
    }
    else
    {
        printf("Why single bank?\n");
    }

    return ret;
}

/**********************************************************************************************************************
 * Function Name: main
 * Summary:
 *  This is the main function.
 *  This function sets up user tasks and then starts the RTOS scheduler.
 * Parameters:
 *  none
 * Return:
 *  int
 **********************************************************************************************************************
 */
int main(void)
{
    cy_rslt_t result;

    /* Initialize the board support package */
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Initialize retarget-io to use the debug UART port. */
    result = cy_retarget_io_init(CYBSP_DEBUG_UART_TX, CYBSP_DEBUG_UART_RX, CY_RETARGET_IO_BAUDRATE);
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Enable global interrupts */
    __enable_irq();

    result = cy_log_init( CY_LOG_INFO, NULL, NULL );
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* \x1b[2J\x1b[;H - ANSI ESC sequence for clear screen */
    printf("\x1b[2J\x1b[;H");
    printf("===========================================================\n");
    printf("Welcome to the AWS IoT OTA demo\n");
    printf("===========================================================\n");

    checkBank();

    cy_log_init(CY_LOG_INFO, NULL, NULL);

    /* Create the FOTA main task. */
    xTaskCreate(otaMqttAppTask, "OTA MQTT APP TASK", OTA_MQTT_APP_TASK_SIZE,
            NULL, OTA_MQTT_APP_TASK_PRIORITY, &g_otaMqttAppTaskHandle);

    /* Start the FreeRTOS scheduler. */
    vTaskStartScheduler();

    /* Should never get here. */
    CY_ASSERT(0);
}

/* [] END OF FILE */
