/**********************************************************************************************************************
 * \file secure_config_cf.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <stddef.h>
#include "cmsis_compiler.h"
#include "cy_utils.h"
#include "secure_config.h"
#include "keystorage.h"
#include "appversion.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* CM0+ ARM CPUID[15:4] Reg shifted to [31:20] */
#define CY_SI_CPUID           (0xC6000000UL)

/* Index ID of the CM0+ core */
#define CY_SI_CORE_IDX        (0UL)

/* The application size (refers linker symbol) */
#define CY_SI_SIZE            ((uint32_t) __si_size_linker_symbol)

/* CM0+ VT Offset (refers linker symbol) */
#define CY_SI_VT_OFFSET       ((uint32_t)__si_vector_offset_linker_symbol) \
                               - offsetof(cy_stc_si_appheader_t, core0Vt)

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* linker symbols */
extern const char __si_vector_offset_linker_symbol[];
extern const char __si_size_linker_symbol[];
extern const char __cy_sf_app_header_start__[];

/* Secure Application header for the CodeFlash application */
CY_SECTION(".cy_app_header") __USED static const cy_stc_si_appheader_t cy_si_codeflash_appHeader =
{
    .objSize        = CY_SI_SIZE,
    .appId          = ((APP_VERSION_MAJOR << 24) | (APP_VERSION_MINOR << 16) | APP_VERSION_BUILD),
    .appAttributes  = 0UL,                            /* Reserved */
    .numCores       = 1UL,                            /* Only CM0+ */
    .core0Vt        = CY_SI_VT_OFFSET,                /* CM0+ VT offset */
    .core0Id        = CY_SI_CPUID | CY_SI_CORE_IDX,   /* CM0+ core ID */
};

/* Secure Image Digital signature (Populated by cymcuelftool) */
CY_SECTION(".cy_app_signature") __USED CY_ALIGN(4)
static const uint8_t cy_si_appSignature[CY_SI_SECURE_DIGSIG_SIZE] = {0u};

/* [] END OF FILE */
